server:
  port: 8771
spring:
  application:
    name: consumer1
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/,http://localhost:8761/eureka/

feign:
  hystrix:
    enabled:  true